Fixed wrong combined path on windows
metarhia/sandboxed-fs pull request #7
Opened 2017-10-26 13:20 UTC by SimonSimCity

When using this method on a `nodejs` installation running on a windows-machine, `path.resolve()` will always prefix your path with - not only the slash, like on unix-systems but also - with the character of the current mounted disk. In my case, this method, when called as `makePathSafe('test.js')`, it returned `C:/test.js`.

This value then always is joined with the path you registered as base-path. In my case it then turned out to be `C:/Users/Administrator/Downloads/C:/test.js`, which obviously has a `C:` too much 😉 

I've tried to remove it here, and it works in all the cases I could test it with. It removes the characters the root of this path has, which (in case of windows) is `C:/`. On a unix system, it only removes the `/` which anyways will be added using the `path.join()`.

2017-10-30 12:40 UTC, belochub commented
First of all, thanks a lot for the contribution!

When this package was developed, the fact that it's going to be used on Windows systems wasn't even considered, and despite this issue being known, we didn't try to fix it at all. You did a great job by finding a small and simple solution to the problem.

However, I'd like to point out that additional path parsing and finding a substring on every call are excessive on Unix systems, and I think, it'll be better to check and fix the path only when running on Windows system.
Other than that, this PR is good to go, failing bitHound checks are not related to the changes, meaning we can ignore them when landing it.

2017-11-01 09:05 UTC, SimonSimCity commented
Thanks for the congrats and the feedback.

I've done some additional research and changed the implementation based on this. I don't know how expensive it is to run `path.parse()` - but I've tried to push it as far out as possible. It will now only run if your system is detected as a windows (also `cygwin` or `msys` are included here) and the path is a unc-path. On this combination the length of the root-path can always differ. Otherwise it's pretty stable to one character on UNIX like systems (the slash `/`, which can safely been ignored) and the three-characters prefix on non-unc paths on windows: `C:\`.

2017-11-01 16:06 UTC, nechaido requested changes

2017-11-01 16:06 UTC, nechaido commented on sandboxed-fs.js
> +  // As Windows is the only non-UNIX like platform supported by node (https://github.com/nodejs/node/blob/master/BUILDING.md#supported-platforms-1)
Line length should not exceed 80 characters.

2017-11-01 16:06 UTC, nechaido commented on sandboxed-fs.js
> +      // If the path is a non-unc path on windows, the root is fixed to 3 characters like 'C:\'
Ditto.

2017-11-01 16:53 UTC, nechaido commented on sandboxed-fs.js
> +const isWindows = require('is-windows');
PTAL at https://nodejs.org/api/process.html#process_process_platform.

2017-11-01 18:42 UTC, SimonSimCity commented
@nechaido that's what the plugin does - including taking care of some simulating platforms like cygwin ...

2017-11-01 20:13 UTC, nechaido commented
@SimonSimCity that's because I dismissed that comment. It is ok to use that package, though I would prefer to write the check manually instead.

2017-11-02 00:14 UTC, tshemsedinov requested changes
You need to remove dependencies: `is-windows` and `is-unc-path`. We try to minimize third-party dependencies if it can be implemented easily.

2017-11-02 05:56 UTC, SimonSimCity commented
Removed the dependencies ... @tshemsedinov but I wonder what your concerns are here. Please explain. Is it just religious, or do you have a reason why?

2017-11-06 15:03 UTC, nechaido approved these changes

2017-11-13 05:27 UTC, SimonSimCity commented
@tshemsedinov is it OK from your side, can this be merged?

2017-11-13 23:51 UTC, tshemsedinov approved these changes

2017-11-13 23:53 UTC, tshemsedinov commented
@SimonSimCity Approved. This module is a part of tech stack Metarhia and it's concept requires to minimize dependencies if possible. So you see, solution is simple.

2017-11-14 00:22 UTC, belochub commented
@SimonSimCity, as far as I know, you can't just copy the code licensed under the MIT license like you did, you have to include the license with it as well.
According to this license:
> The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

Also, in my opinion, there is still a way to slightly improve performance. I think the platform check can be done just once, during the module load, and the function for making file paths safe can at the same time be dynamically assigned according to the platform.

2017-11-14 05:31 UTC, SimonSimCity commented
Is it really a licensing problem, since this code is licensed under MIT as well? If it is, please sort out a solution with @tshemsedinov since I don't know much about legal stuff, but am happy to take the implementation once it's clear.

The performance improvement you're talking about here is neglectable in my eyes, because we have a comparison on a fixed primitive value, which can and will be optimized by the JIT compiler. If not, we're talking about an improvement of less than a pico-second on 1k runs against code, that's harder to read and maintain.

2017-11-22 11:01 UTC, SimonSimCity commented
Any comment on this one @belochub @tshemsedinov? I'd like to get this in a new release, so also others have the chance to use this package on windows.

2018-02-05 07:48 UTC, SimonSimCity commented
What's still keeping this from being merged?

2018-02-05 11:07 UTC, belochub commented
I am truly sorry for such a delay in resolving this PR.

> Is it really a licensing problem, since this code is licensed under MIT as well?

Answering your question about licensing, this is actually a problem since MIT license applies to the original code, and the licensing of the code you copy this original code into has no effect on the terms of the original license. Having this in mind we need to honor the MIT license in the point that
> The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

Without changing the current code I don't see any other solution except including the licenses of the packages, you copied the code from, into the project.

2018-02-05 11:41 UTC, SimonSimCity commented
@belochub isn't it already? https://github.com/metarhia/sandboxed-fs/blob/master/LICENSE

2018-02-05 13:02 UTC, belochub commented
I am not sure what you are referring to here, but the license file you mentioned in your reply does not include licenses from packages you have copied the code from (available at https://github.com/jonschlinkert/is-windows/blob/master/LICENSE and https://github.com/jonschlinkert/is-unc-path/blob/master/LICENSE).

2018-02-05 14:01 UTC, SimonSimCity commented
@belochub Ok, I don't get the difference. All these products are licensed under MIT and I neither know what steps to take.

I don't see how you want me to include these licenses in here without copying the full license as code-comment, which seems ridiculous to me. But as I said, I have no insight on legal issues. I'd also be fine if you take my fork, adjust it by the needed stuff and merge it into the main repo here.

2018-02-05 15:28 UTC, belochub commented
@SimonSimCity, I've updated the license and fixed some errors reported by `eslint`, I think one approve from either @nechaido or @tshemsedinov will be enough to land this PR at the moment.

2018-02-05 15:29 UTC, nechaido approved these changes

2018-02-05 15:35 UTC, belochub commented
Landed in https://github.com/metarhia/sandboxed-fs/commit/24576844149129bf641792b991df109f41e3d973.
Congratulations and thanks for the contribution!
I will publish the updated package as soon as possible now.

2018-02-05 15:35 UTC, closed without merging